groups:
  - name: lab
    rules:
      - alert: ExporterDown
        expr: up{job="lab-exporter"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Lab exporter is down"
      - alert: HighCPUDemo
        expr: lab_cpu_usage_percent > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Demo CPU high"
