{
 "title": "Runnable Lab Overview",
 "tags": [
  "lab",
  "portfolio"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU % (demo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "lab_cpu_usage_percent", "legendFormat": "cpu" }
   ]
  },
  {
   "title": "Memory % (demo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "lab_memory_usage_percent", "legendFormat": "mem" }
   ]
  },
  {
   "title": "Exporter up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lab_up" }
   ]
  }
 ]
}